env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  # Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
  - "prettier/@typescript-eslint"
  # Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors.
  # Make sure this is always the last configuration in the extends array.
  - "plugin:prettier/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-unused-vars": [ "warn", { argsIgnorePattern: "^_" } ]
